### ISSUE TITLE
Mover as pastas de GUI e imagens para dentro da pasta SRC

### ISSUE THREAD

**Issue by gidaltijunior** [gidaltijunior/cotolengo#2]
Tive problemas em criar o ambiente de desenvolvimento no Windows pois o código não encontrava o caminho para a pasta GLADE e IMAGENS. No Linux funciona perfeitamente.
Portanto, para referenciar arquivos GLADE e IMAGENS mais facilmente, o melhor seria movê-los para dentro da pasta SRC.
Isso requer algum esforço pois é necessário renomear os caminhos dentro dos códigos-fonte e, possivelmente, o caminho para as imagens de dentro dos arquivos GLADE.

Baixa prioridade.

**Comment by gidaltijunior** [comment]
O problema na verdade ocorre dependendo de onde o arquivo é executado.

Exemplo de falha:
```
me@mycomputer:~/Project/src$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    login = Login()
  File "/home/me/Project/src/login.py", line 15, in __init__
    builder.add_from_file('glade/tela_login.glade')
GLib.Error: g-file-error-quark: Falha ao abrir arquivo "glade/tela_login.glade": No such file or directory (4)
```
No entanto, se o arquivo main.py for executado da pasta root, o erro não ocorre:
```
me@mycomputer:~/Project$ python3 src/main.py 
Tentativa de conexão com o banco da dados iniciada.
```

**Comment by gidaltijunior** [comment]
Essa tarefa está pendente.

Os benefícios trazidos por essa tarefa não estão claros.

**Comment by marcospsviana** [comment]
No meu caso consegui resolver especificando o caminho absoluto do arquivo .glade por exemplo:
**`builder.add_from_file("/caminho _do_app/dist/sua_gui.glade")`** .
depois gerar o executavel com o pyinstaller
